-- SCRIPT COMPLETO DE DEPARTAMENTOS Y MUNICIPIOS DE COLOMBIA (CARGA MASIVA)
-- UTP CONTROL INTELLIGENCE - SISTEMA DINÁMICO

-- 1. REGIONES (DEPARTAMENTOS)
INSERT INTO regions (id, name, code) VALUES
('DEPT-05', 'Antioquia', 'ANT'),
('DEPT-08', 'Atlántico', 'ATL'),
('DEPT-11', 'Bogotá D.C.', 'BOG'),
('DEPT-13', 'Bolívar', 'BOL'),
('DEPT-15', 'Boyacá', 'BOY'),
('DEPT-17', 'Caldas', 'CAL'),
('DEPT-18', 'Caquetá', 'CAQ'),
('DEPT-19', 'Cauca', 'CAU'),
('DEPT-20', 'Cesar', 'CES'),
('DEPT-23', 'Córdoba', 'COR'),
('DEPT-25', 'Cundinamarca', 'CUN'),
('DEPT-27', 'Chocó', 'CHO'),
('DEPT-41', 'Huila', 'HUI'),
('DEPT-44', 'La Guajira', 'LAG'),
('DEPT-47', 'Magdalena', 'MAG'),
('DEPT-50', 'Meta', 'MET'),
('DEPT-52', 'Nariño', 'NAR'),
('DEPT-54', 'Norte de Santander', 'NSA'),
('DEPT-63', 'Quindío', 'QUI'),
('DEPT-66', 'Risaralda', 'RIS'),
('DEPT-68', 'Santander', 'SAN'),
('DEPT-70', 'Sucre', 'SUC'),
('DEPT-73', 'Tolima', 'TOL'),
('DEPT-76', 'Valle del Cauca', 'VAC'),
('DEPT-81', 'Arauca', 'ARA'),
('DEPT-85', 'Casanare', 'CAS'),
('DEPT-86', 'Putumayo', 'PUT'),
('DEPT-88', 'San Andrés', 'SAP'),
('DEPT-91', 'Amazonas', 'AMA'),
('DEPT-94', 'Guainía', 'GUA'),
('DEPT-95', 'Guaviare', 'GUV'),
('DEPT-97', 'Vaupés', 'VAU'),
('DEPT-99', 'Vichada', 'VIC')
ON CONFLICT (code) DO NOTHING;

-- 2. MUNICIPIOS (MUESTRA EXTENSIVA POR DEPARTAMENTO)
INSERT INTO municipalities (id, name, region_id) VALUES
-- ANTIOQUIA (05)
(gen_random_uuid(), 'Medellín', 'DEPT-05'), (gen_random_uuid(), 'Abejorral', 'DEPT-05'), (gen_random_uuid(), 'Abriaquí', 'DEPT-05'), (gen_random_uuid(), 'Alejandría', 'DEPT-05'),
(gen_random_uuid(), 'Amagá', 'DEPT-05'), (gen_random_uuid(), 'Amalfi', 'DEPT-05'), (gen_random_uuid(), 'Andes', 'DEPT-05'), (gen_random_uuid(), 'Angelópolis', 'DEPT-05'),
(gen_random_uuid(), 'Angostura', 'DEPT-05'), (gen_random_uuid(), 'Anorí', 'DEPT-05'), (gen_random_uuid(), 'Santa Fe de Antioquia', 'DEPT-05'), (gen_random_uuid(), 'Anzá', 'DEPT-05'),
(gen_random_uuid(), 'Apartadó', 'DEPT-05'), (gen_random_uuid(), 'Arboletes', 'DEPT-05'), (gen_random_uuid(), 'Argelia', 'DEPT-05'), (gen_random_uuid(), 'Armenia', 'DEPT-05'),
(gen_random_uuid(), 'Barbosa', 'DEPT-05'), (gen_random_uuid(), 'Belmira', 'DEPT-05'), (gen_random_uuid(), 'Bello', 'DEPT-05'), (gen_random_uuid(), 'Betania', 'DEPT-05'),
(gen_random_uuid(), 'Betulia', 'DEPT-05'), (gen_random_uuid(), 'Ciudad Bolívar', 'DEPT-05'), (gen_random_uuid(), 'Briceño', 'DEPT-05'), (gen_random_uuid(), 'Buriticá', 'DEPT-05'),
(gen_random_uuid(), 'Cáceres', 'DEPT-05'), (gen_random_uuid(), 'Caicedo', 'DEPT-05'), (gen_random_uuid(), 'Caldas', 'DEPT-05'), (gen_random_uuid(), 'Campamento', 'DEPT-05'),
(gen_random_uuid(), 'Cañasgordas', 'DEPT-05'), (gen_random_uuid(), 'Caracolí', 'DEPT-05'), (gen_random_uuid(), 'Caramanta', 'DEPT-05'), (gen_random_uuid(), 'Carepa', 'DEPT-05'),
(gen_random_uuid(), 'Carmen de Viboral', 'DEPT-05'), (gen_random_uuid(), 'Carolina del Príncipe', 'DEPT-05'), (gen_random_uuid(), 'Caucasia', 'DEPT-05'), (gen_random_uuid(), 'Chigorodó', 'DEPT-05'),
(gen_random_uuid(), 'Cisneros', 'DEPT-05'), (gen_random_uuid(), 'Cocorná', 'DEPT-05'), (gen_random_uuid(), 'Concepción', 'DEPT-05'), (gen_random_uuid(), 'Concordia', 'DEPT-05'),
(gen_random_uuid(), 'Copacabana', 'DEPT-05'), (gen_random_uuid(), 'Dabeiba', 'DEPT-05'), (gen_random_uuid(), 'Donmatías', 'DEPT-05'), (gen_random_uuid(), 'Ebéjico', 'DEPT-05'),
(gen_random_uuid(), 'El Bagre', 'DEPT-05'), (gen_random_uuid(), 'Entrerríos', 'DEPT-05'), (gen_random_uuid(), 'Envigado', 'DEPT-05'), (gen_random_uuid(), 'Fredonia', 'DEPT-05'),
(gen_random_uuid(), 'Frontino', 'DEPT-05'), (gen_random_uuid(), 'Giraldo', 'DEPT-05'), (gen_random_uuid(), 'Girardota', 'DEPT-05'), (gen_random_uuid(), 'Gómez Plata', 'DEPT-05'),
(gen_random_uuid(), 'Granada', 'DEPT-05'), (gen_random_uuid(), 'Guadalupe', 'DEPT-05'), (gen_random_uuid(), 'Guarne', 'DEPT-05'), (gen_random_uuid(), 'Guatapé', 'DEPT-05'),
(gen_random_uuid(), 'Heliconia', 'DEPT-05'), (gen_random_uuid(), 'Hispania', 'DEPT-05'), (gen_random_uuid(), 'Itagüí', 'DEPT-05'), (gen_random_uuid(), 'Ituango', 'DEPT-05'),
(gen_random_uuid(), 'Jardín', 'DEPT-05'), (gen_random_uuid(), 'Jericó', 'DEPT-05'), (gen_random_uuid(), 'La Ceja', 'DEPT-05'), (gen_random_uuid(), 'La Estrella', 'DEPT-05'),
(gen_random_uuid(), 'La Pintada', 'DEPT-05'), (gen_random_uuid(), 'La Unión', 'DEPT-05'), (gen_random_uuid(), 'Liborina', 'DEPT-05'), (gen_random_uuid(), 'Maceo', 'DEPT-05'),
(gen_random_uuid(), 'Marinilla', 'DEPT-05'), (gen_random_uuid(), 'Montebello', 'DEPT-05'), (gen_random_uuid(), 'Murindó', 'DEPT-05'), (gen_random_uuid(), 'Mutatá', 'DEPT-05'),
(gen_random_uuid(), 'Nariño', 'DEPT-05'), (gen_random_uuid(), 'Necoclí', 'DEPT-05'), (gen_random_uuid(), 'Nechí', 'DEPT-05'), (gen_random_uuid(), 'Olaya', 'DEPT-05'),
(gen_random_uuid(), 'Peñol', 'DEPT-05'), (gen_random_uuid(), 'Peque', 'DEPT-05'), (gen_random_uuid(), 'Pueblorrico', 'DEPT-05'), (gen_random_uuid(), 'Puerto Berrío', 'DEPT-05'),
(gen_random_uuid(), 'Puerto Nare', 'DEPT-05'), (gen_random_uuid(), 'Puerto Triunfo', 'DEPT-05'), (gen_random_uuid(), 'Remedios', 'DEPT-05'), (gen_random_uuid(), 'Retiro', 'DEPT-05'),
(gen_random_uuid(), 'Rionegro', 'DEPT-05'), (gen_random_uuid(), 'Sabanalarga', 'DEPT-05'), (gen_random_uuid(), 'Sabaneta', 'DEPT-05'), (gen_random_uuid(), 'Salgar', 'DEPT-05'),
(gen_random_uuid(), 'San Andrés de Cuerquia', 'DEPT-05'), (gen_random_uuid(), 'San Carlos', 'DEPT-05'), (gen_random_uuid(), 'San Francisco', 'DEPT-05'), (gen_random_uuid(), 'San Jerónimo', 'DEPT-05'),
(gen_random_uuid(), 'San José de la Montaña', 'DEPT-05'), (gen_random_uuid(), 'San Juan de Urabá', 'DEPT-05'), (gen_random_uuid(), 'San Luis', 'DEPT-05'), (gen_random_uuid(), 'San Pedro de los Milagros', 'DEPT-05'),
(gen_random_uuid(), 'San Pedro de Urabá', 'DEPT-05'), (gen_random_uuid(), 'San Rafael', 'DEPT-05'), (gen_random_uuid(), 'San Roque', 'DEPT-05'), (gen_random_uuid(), 'San Vicente', 'DEPT-05'),
(gen_random_uuid(), 'Santa Bárbara', 'DEPT-05'), (gen_random_uuid(), 'Santa Rosa de Osos', 'DEPT-05'), (gen_random_uuid(), 'Santo Domingo', 'DEPT-05'), (gen_random_uuid(), 'Santuario', 'DEPT-05'),
(gen_random_uuid(), 'Segovia', 'DEPT-05'), (gen_random_uuid(), 'Sonson', 'DEPT-05'), (gen_random_uuid(), 'Sopetrán', 'DEPT-05'), (gen_random_uuid(), 'Támesis', 'DEPT-05'),
(gen_random_uuid(), 'Tarazá', 'DEPT-05'), (gen_random_uuid(), 'Tarso', 'DEPT-05'), (gen_random_uuid(), 'Titiribí', 'DEPT-05'), (gen_random_uuid(), 'Toledo', 'DEPT-05'),
(gen_random_uuid(), 'Turbo', 'DEPT-05'), (gen_random_uuid(), 'Uramita', 'DEPT-05'), (gen_random_uuid(), 'Urrao', 'DEPT-05'), (gen_random_uuid(), 'Valdivia', 'DEPT-05'),
(gen_random_uuid(), 'Valparaíso', 'DEPT-05'), (gen_random_uuid(), 'Vegachí', 'DEPT-05'), (gen_random_uuid(), 'Venecia', 'DEPT-05'), (gen_random_uuid(), 'Vigía del Fuerte', 'DEPT-05'),
(gen_random_uuid(), 'Yalí', 'DEPT-05'), (gen_random_uuid(), 'Yarumal', 'DEPT-05'), (gen_random_uuid(), 'Yolombó', 'DEPT-05'), (gen_random_uuid(), 'Yondó', 'DEPT-05'),
(gen_random_uuid(), 'Zaragoza', 'DEPT-05'),

-- ATLANTICO (08)
(gen_random_uuid(), 'Barranquilla', 'DEPT-08'), (gen_random_uuid(), 'Baranoa', 'DEPT-08'), (gen_random_uuid(), 'Campo de la Cruz', 'DEPT-08'), (gen_random_uuid(), 'Candelaria', 'DEPT-08'),
(gen_random_uuid(), 'Galapa', 'DEPT-08'), (gen_random_uuid(), 'Juan de Acosta', 'DEPT-08'), (gen_random_uuid(), 'Luruaco', 'DEPT-08'), (gen_random_uuid(), 'Malambo', 'DEPT-08'),
(gen_random_uuid(), 'Manatí', 'DEPT-08'), (gen_random_uuid(), 'Palmar de Varela', 'DEPT-08'), (gen_random_uuid(), 'Piojó', 'DEPT-08'), (gen_random_uuid(), 'Polonuevo', 'DEPT-08'),
(gen_random_uuid(), 'Ponedera', 'DEPT-08'), (gen_random_uuid(), 'Puerto Colombia', 'DEPT-08'), (gen_random_uuid(), 'Repelón', 'DEPT-08'), (gen_random_uuid(), 'Sabanagrande', 'DEPT-08'),
(gen_random_uuid(), 'Sabanalarga', 'DEPT-08'), (gen_random_uuid(), 'Santa Lucía', 'DEPT-08'), (gen_random_uuid(), 'Santo Tomás', 'DEPT-08'), (gen_random_uuid(), 'Soledad', 'DEPT-08'),
(gen_random_uuid(), 'Suan', 'DEPT-08'), (gen_random_uuid(), 'Tubará', 'DEPT-08'), (gen_random_uuid(), 'Usiacurí', 'DEPT-08'),

-- BOLIVAR (13)
(gen_random_uuid(), 'Cartagena de Indias', 'DEPT-13'), (gen_random_uuid(), 'Achí', 'DEPT-13'), (gen_random_uuid(), 'Altos del Rosario', 'DEPT-13'), (gen_random_uuid(), 'Arenal', 'DEPT-13'),
(gen_random_uuid(), 'Arjona', 'DEPT-13'), (gen_random_uuid(), 'Arroyohondo', 'DEPT-13'), (gen_random_uuid(), 'Barranco de Loba', 'DEPT-13'), (gen_random_uuid(), 'Calamar', 'DEPT-13'),
(gen_random_uuid(), 'Cantagallo', 'DEPT-13'), (gen_random_uuid(), 'Cicuco', 'DEPT-13'), (gen_random_uuid(), 'Córdoba', 'DEPT-13'), (gen_random_uuid(), 'Clemencia', 'DEPT-13'),
(gen_random_uuid(), 'El Carmen de Bolívar', 'DEPT-13'), (gen_random_uuid(), 'El Guamo', 'DEPT-13'), (gen_random_uuid(), 'El Peñón', 'DEPT-13'), (gen_random_uuid(), 'Hatillo de Loba', 'DEPT-13'),
(gen_random_uuid(), 'Magangué', 'DEPT-13'), (gen_random_uuid(), 'Mahates', 'DEPT-13'), (gen_random_uuid(), 'Margarita', 'DEPT-13'), (gen_random_uuid(), 'María la Baja', 'DEPT-13'),
(gen_random_uuid(), 'Mompós', 'DEPT-13'), (gen_random_uuid(), 'Montecristo', 'DEPT-13'), (gen_random_uuid(), 'Morales', 'DEPT-13'), (gen_random_uuid(), 'Pinillos', 'DEPT-13'),
(gen_random_uuid(), 'Regidor', 'DEPT-13'), (gen_random_uuid(), 'Río Viejo', 'DEPT-13'), (gen_random_uuid(), 'San Cristóbal', 'DEPT-13'), (gen_random_uuid(), 'San Estanislao', 'DEPT-13'),
(gen_random_uuid(), 'San Fernando', 'DEPT-13'), (gen_random_uuid(), 'San Jacinto', 'DEPT-13'), (gen_random_uuid(), 'San Jacinto del Cauca', 'DEPT-13'), (gen_random_uuid(), 'San Juan Nepomuceno', 'DEPT-13'),
(gen_random_uuid(), 'San Martín de Loba', 'DEPT-13'), (gen_random_uuid(), 'San Pablo', 'DEPT-13'), (gen_random_uuid(), 'Santa Catalina', 'DEPT-13'), (gen_random_uuid(), 'Santa Rosa', 'DEPT-13'),
(gen_random_uuid(), 'Santa Rosa del Sur', 'DEPT-13'), (gen_random_uuid(), 'Simití', 'DEPT-13'), (gen_random_uuid(), 'Soplaviento', 'DEPT-13'), (gen_random_uuid(), 'Talaigua Nuevo', 'DEPT-13'),
(gen_random_uuid(), 'Tiquisio', 'DEPT-13'), (gen_random_uuid(), 'Turbaco', 'DEPT-13'), (gen_random_uuid(), 'Turbaná', 'DEPT-13'), (gen_random_uuid(), 'Villanueva', 'DEPT-13'),
(gen_random_uuid(), 'Zambrano', 'DEPT-13'),

-- BOYACA (15)
(gen_random_uuid(), 'Tunja', 'DEPT-15'), (gen_random_uuid(), 'Almeida', 'DEPT-15'), (gen_random_uuid(), 'Aquitania', 'DEPT-15'), (gen_random_uuid(), 'Arcabuco', 'DEPT-15'),
(gen_random_uuid(), 'Belén', 'DEPT-15'), (gen_random_uuid(), 'Berbeo', 'DEPT-15'), (gen_random_uuid(), 'Betéitiva', 'DEPT-15'), (gen_random_uuid(), 'Boavita', 'DEPT-15'),
(gen_random_uuid(), 'Boyacá', 'DEPT-15'), (gen_random_uuid(), 'Briceño', 'DEPT-15'), (gen_random_uuid(), 'Buenavista', 'DEPT-15'), (gen_random_uuid(), 'Busbanzá', 'DEPT-15'),
(gen_random_uuid(), 'Caldas', 'DEPT-15'), (gen_random_uuid(), 'Campohermoso', 'DEPT-15'), (gen_random_uuid(), 'Cerinza', 'DEPT-15'), (gen_random_uuid(), 'Chinavita', 'DEPT-15'),
(gen_random_uuid(), 'Chiquinquirá', 'DEPT-15'), (gen_random_uuid(), 'Chiscas', 'DEPT-15'), (gen_random_uuid(), 'Chita', 'DEPT-15'), (gen_random_uuid(), 'Chitaraque', 'DEPT-15'),
(gen_random_uuid(), 'Chivatá', 'DEPT-15'), (gen_random_uuid(), 'Ciénega', 'DEPT-15'), (gen_random_uuid(), 'Cómbita', 'DEPT-15'), (gen_random_uuid(), 'Coper', 'DEPT-15'),
(gen_random_uuid(), 'Corrales', 'DEPT-15'), (gen_random_uuid(), 'Covarachía', 'DEPT-15'), (gen_random_uuid(), 'Cubará', 'DEPT-15'), (gen_random_uuid(), 'Cucaita', 'DEPT-15'),
(gen_random_uuid(), 'Cuítiva', 'DEPT-15'), (gen_random_uuid(), 'Chíquiza', 'DEPT-15'), (gen_random_uuid(), 'Chivor', 'DEPT-15'), (gen_random_uuid(), 'Duitama', 'DEPT-15'),
(gen_random_uuid(), 'El Cocuy', 'DEPT-15'), (gen_random_uuid(), 'El Espino', 'DEPT-15'), (gen_random_uuid(), 'Firavitoba', 'DEPT-15'), (gen_random_uuid(), 'Floresta', 'DEPT-15'),
(gen_random_uuid(), 'Gachantivá', 'DEPT-15'), (gen_random_uuid(), 'Gameza', 'DEPT-15'), (gen_random_uuid(), 'Garagoa', 'DEPT-15'), (gen_random_uuid(), 'Guacamayas', 'DEPT-15'),
(gen_random_uuid(), 'Guateque', 'DEPT-15'), (gen_random_uuid(), 'Guayatá', 'DEPT-15'), (gen_random_uuid(), 'Güicán', 'DEPT-15'), (gen_random_uuid(), 'Iza', 'DEPT-15'),
(gen_random_uuid(), 'Jenesano', 'DEPT-15'), (gen_random_uuid(), 'Jericó', 'DEPT-15'), (gen_random_uuid(), 'Labranzagrande', 'DEPT-15'), (gen_random_uuid(), 'La Capilla', 'DEPT-15'),
(gen_random_uuid(), 'La Victoria', 'DEPT-15'), (gen_random_uuid(), 'La Uvita', 'DEPT-15'), (gen_random_uuid(), 'Leiva', 'DEPT-15'), (gen_random_uuid(), 'Macanal', 'DEPT-15'),
(gen_random_uuid(), 'Maripí', 'DEPT-15'), (gen_random_uuid(), 'Miraflores', 'DEPT-15'), (gen_random_uuid(), 'Mongua', 'DEPT-15'), (gen_random_uuid(), 'Monguí', 'DEPT-15'),
(gen_random_uuid(), 'Moniquirá', 'DEPT-15'), (gen_random_uuid(), 'Motavita', 'DEPT-15'), (gen_random_uuid(), 'Muzo', 'DEPT-15'), (gen_random_uuid(), 'Nobsa', 'DEPT-15'),
(gen_random_uuid(), 'Nuevo Colón', 'DEPT-15'), (gen_random_uuid(), 'Oicatá', 'DEPT-15'), (gen_random_uuid(), 'Otanche', 'DEPT-15'), (gen_random_uuid(), 'Pachavita', 'DEPT-15'),
(gen_random_uuid(), 'Páez', 'DEPT-15'), (gen_random_uuid(), 'Paipa', 'DEPT-15'), (gen_random_uuid(), 'Pajarito', 'DEPT-15'), (gen_random_uuid(), 'Panqueba', 'DEPT-15'),
(gen_random_uuid(), 'Pauna', 'DEPT-15'), (gen_random_uuid(), 'Paya', 'DEPT-15'), (gen_random_uuid(), 'Paz de Río', 'DEPT-15'), (gen_random_uuid(), 'Pesca', 'DEPT-15'),
(gen_random_uuid(), 'Pisba', 'DEPT-15'), (gen_random_uuid(), 'Puerto Boyacá', 'DEPT-15'), (gen_random_uuid(), 'Quípama', 'DEPT-15'), (gen_random_uuid(), 'Ramiriquí', 'DEPT-15'),
(gen_random_uuid(), 'Ráquira', 'DEPT-15'), (gen_random_uuid(), 'Rondón', 'DEPT-15'), (gen_random_uuid(), 'Saboyá', 'DEPT-15'), (gen_random_uuid(), 'Sáchica', 'DEPT-15'),
(gen_random_uuid(), 'Samacá', 'DEPT-15'), (gen_random_uuid(), 'San Eduardo', 'DEPT-15'), (gen_random_uuid(), 'San José de Pare', 'DEPT-15'), (gen_random_uuid(), 'San Mateo', 'DEPT-15'),
(gen_random_uuid(), 'San Miguel de Sema', 'DEPT-15'), (gen_random_uuid(), 'San Pablo de Borbur', 'DEPT-15'), (gen_random_uuid(), 'Santana', 'DEPT-15'), (gen_random_uuid(), 'Santa María', 'DEPT-15'),
(gen_random_uuid(), 'Santa Rosa de Viterbo', 'DEPT-15'), (gen_random_uuid(), 'Santa Sofía', 'DEPT-15'), (gen_random_uuid(), 'Sativanorte', 'DEPT-15'), (gen_random_uuid(), 'Sativasur', 'DEPT-15'),
(gen_random_uuid(), 'Siachoque', 'DEPT-15'), (gen_random_uuid(), 'Soatá', 'DEPT-15'), (gen_random_uuid(), 'Socotá', 'DEPT-15'), (gen_random_uuid(), 'Socha', 'DEPT-15'),
(gen_random_uuid(), 'Sogamoso', 'DEPT-15'), (gen_random_uuid(), 'Somondoco', 'DEPT-15'), (gen_random_uuid(), 'Sora', 'DEPT-15'), (gen_random_uuid(), 'Sotaquirá', 'DEPT-15'),
(gen_random_uuid(), 'Soracá', 'DEPT-15'), (gen_random_uuid(), 'Susacón', 'DEPT-15'), (gen_random_uuid(), 'Sutamarchán', 'DEPT-15'), (gen_random_uuid(), 'Sutatenza', 'DEPT-15'),
(gen_random_uuid(), 'Tasco', 'DEPT-15'), (gen_random_uuid(), 'Tenza', 'DEPT-15'), (gen_random_uuid(), 'Tibaná', 'DEPT-15'), (gen_random_uuid(), 'Tibasosa', 'DEPT-15'),
(gen_random_uuid(), 'Tinjacá', 'DEPT-15'), (gen_random_uuid(), 'Tipacoque', 'DEPT-15'), (gen_random_uuid(), 'Toca', 'DEPT-15'), (gen_random_uuid(), 'Togüí', 'DEPT-15'),
(gen_random_uuid(), 'Tópaga', 'DEPT-15'), (gen_random_uuid(), 'Tota', 'DEPT-15'), (gen_random_uuid(), 'Tununguá', 'DEPT-15'), (gen_random_uuid(), 'Turmequé', 'DEPT-15'),
(gen_random_uuid(), 'Tuta', 'DEPT-15'), (gen_random_uuid(), 'Tutazá', 'DEPT-15'), (gen_random_uuid(), 'Umbita', 'DEPT-15'), (gen_random_uuid(), 'Ventaquemada', 'DEPT-15'),
(gen_random_uuid(), 'Viracachá', 'DEPT-15'), (gen_random_uuid(), 'Zetaquira', 'DEPT-15'),

-- CUNDINAMARCA (25)
(gen_random_uuid(), 'Bogotá D.C.', 'DEPT-25'), (gen_random_uuid(), 'Agua de Dios', 'DEPT-25'), (gen_random_uuid(), 'Albán', 'DEPT-25'), (gen_random_uuid(), 'Anapoima', 'DEPT-25'),
(gen_random_uuid(), 'Anolaima', 'DEPT-25'), (gen_random_uuid(), 'Arbeláez', 'DEPT-25'), (gen_random_uuid(), 'Beltrán', 'DEPT-25'), (gen_random_uuid(), 'Bituima', 'DEPT-25'),
(gen_random_uuid(), 'Bojacá', 'DEPT-25'), (gen_random_uuid(), 'Cabrera', 'DEPT-25'), (gen_random_uuid(), 'Cachipay', 'DEPT-25'), (gen_random_uuid(), 'Cajicá', 'DEPT-25'),
(gen_random_uuid(), 'Caparrapí', 'DEPT-25'), (gen_random_uuid(), 'Cáqueza', 'DEPT-25'), (gen_random_uuid(), 'Carmen de Carupa', 'DEPT-25'), (gen_random_uuid(), 'Chaguaní', 'DEPT-25'),
(gen_random_uuid(), 'Chía', 'DEPT-25'), (gen_random_uuid(), 'Chipaque', 'DEPT-25'), (gen_random_uuid(), 'Choachí', 'DEPT-25'), (gen_random_uuid(), 'Chocontá', 'DEPT-25'),
(gen_random_uuid(), 'Cogua', 'DEPT-25'), (gen_random_uuid(), 'Cota', 'DEPT-25'), (gen_random_uuid(), 'Cucunubá', 'DEPT-25'), (gen_random_uuid(), 'El Colegio', 'DEPT-25'),
(gen_random_uuid(), 'El Peñón', 'DEPT-25'), (gen_random_uuid(), 'El Rosal', 'DEPT-25'), (gen_random_uuid(), 'Facatativá', 'DEPT-25'), (gen_random_uuid(), 'Fómeque', 'DEPT-25'),
(gen_random_uuid(), 'Fosca', 'DEPT-25'), (gen_random_uuid(), 'Funza', 'DEPT-25'), (gen_random_uuid(), 'Fúquene', 'DEPT-25'), (gen_random_uuid(), 'Fusagasugá', 'DEPT-25'),
(gen_random_uuid(), 'Gachalá', 'DEPT-25'), (gen_random_uuid(), 'Gachancipá', 'DEPT-25'), (gen_random_uuid(), 'Gachetá', 'DEPT-25'), (gen_random_uuid(), 'Gama', 'DEPT-25'),
(gen_random_uuid(), 'Girardot', 'DEPT-25'), (gen_random_uuid(), 'Granada', 'DEPT-25'), (gen_random_uuid(), 'Guachetá', 'DEPT-25'), (gen_random_uuid(), 'Guaduas', 'DEPT-25'),
(gen_random_uuid(), 'Guasca', 'DEPT-25'), (gen_random_uuid(), 'Guataquí', 'DEPT-25'), (gen_random_uuid(), 'Guatavita', 'DEPT-25'), (gen_random_uuid(), 'Guayabal de Síquima', 'DEPT-25'),
(gen_random_uuid(), 'Guayabetal', 'DEPT-25'), (gen_random_uuid(), 'Gutiérrez', 'DEPT-25'), (gen_random_uuid(), 'Jerusalén', 'DEPT-25'), (gen_random_uuid(), 'Junín', 'DEPT-25'),
(gen_random_uuid(), 'La Calera', 'DEPT-25'), (gen_random_uuid(), 'La Mesa', 'DEPT-25'), (gen_random_uuid(), 'La Palma', 'DEPT-25'), (gen_random_uuid(), 'La Peña', 'DEPT-25'),
(gen_random_uuid(), 'La Vega', 'DEPT-25'), (gen_random_uuid(), 'Lenguazaque', 'DEPT-25'), (gen_random_uuid(), 'Machetá', 'DEPT-25'), (gen_random_uuid(), 'Madrid', 'DEPT-25'),
(gen_random_uuid(), 'Manta', 'DEPT-25'), (gen_random_uuid(), 'Medina', 'DEPT-25'), (gen_random_uuid(), 'Mosquera', 'DEPT-25'), (gen_random_uuid(), 'Nariño', 'DEPT-25'),
(gen_random_uuid(), 'Nemocón', 'DEPT-25'), (gen_random_uuid(), 'Nilo', 'DEPT-25'), (gen_random_uuid(), 'Nimaima', 'DEPT-25'), (gen_random_uuid(), 'Nocaima', 'DEPT-25'),
(gen_random_uuid(), 'Venecia', 'DEPT-25'), (gen_random_uuid(), 'Pacho', 'DEPT-25'), (gen_random_uuid(), 'Paime', 'DEPT-25'), (gen_random_uuid(), 'Pandi', 'DEPT-25'),
(gen_random_uuid(), 'Paratebueno', 'DEPT-25'), (gen_random_uuid(), 'Pasca', 'DEPT-25'), (gen_random_uuid(), 'Puerto Salgar', 'DEPT-25'), (gen_random_uuid(), 'Pulí', 'DEPT-25'),
(gen_random_uuid(), 'Quebradanegra', 'DEPT-25'), (gen_random_uuid(), 'Quetame', 'DEPT-25'), (gen_random_uuid(), 'Quipile', 'DEPT-25'), (gen_random_uuid(), 'Apulo', 'DEPT-25'),
(gen_random_uuid(), 'Ricaurte', 'DEPT-25'), (gen_random_uuid(), 'San Antonio del Tequendama', 'DEPT-25'), (gen_random_uuid(), 'San Bernardo', 'DEPT-25'), (gen_random_uuid(), 'San Cayetano', 'DEPT-25'),
(gen_random_uuid(), 'San Francisco', 'DEPT-25'), (gen_random_uuid(), 'San Juan de Rioseco', 'DEPT-25'), (gen_random_uuid(), 'Sasaima', 'DEPT-25'), (gen_random_uuid(), 'Sesquilé', 'DEPT-25'),
(gen_random_uuid(), 'Sibaté', 'DEPT-25'), (gen_random_uuid(), 'Silvania', 'DEPT-25'), (gen_random_uuid(), 'Simijaca', 'DEPT-25'), (gen_random_uuid(), 'Soacha', 'DEPT-25'),
(gen_random_uuid(), 'Sopó', 'DEPT-25'), (gen_random_uuid(), 'Subachoque', 'DEPT-25'), (gen_random_uuid(), 'Suesca', 'DEPT-25'), (gen_random_uuid(), 'Supatá', 'DEPT-25'),
(gen_random_uuid(), 'Susa', 'DEPT-25'), (gen_random_uuid(), 'Sutatausa', 'DEPT-25'), (gen_random_uuid(), 'Tabio', 'DEPT-25'), (gen_random_uuid(), 'Tausa', 'DEPT-25'),
(gen_random_uuid(), 'Tena', 'DEPT-25'), (gen_random_uuid(), 'Tenjo', 'DEPT-25'), (gen_random_uuid(), 'Tibacuy', 'DEPT-25'), (gen_random_uuid(), 'Tibirita', 'DEPT-25'),
(gen_random_uuid(), 'Tocaima', 'DEPT-25'), (gen_random_uuid(), 'Tocancipá', 'DEPT-25'), (gen_random_uuid(), 'Topaipí', 'DEPT-25'), (gen_random_uuid(), 'Ubalá', 'DEPT-25'),
(gen_random_uuid(), 'Ubaque', 'DEPT-25'), (gen_random_uuid(), 'Villa de San Diego de Ubaté', 'DEPT-25'), (gen_random_uuid(), 'Une', 'DEPT-25'), (gen_random_uuid(), 'Útica', 'DEPT-25'),
(gen_random_uuid(), 'Vergara', 'DEPT-25'), (gen_random_uuid(), 'Vianí', 'DEPT-25'), (gen_random_uuid(), 'Villagómez', 'DEPT-25'), (gen_random_uuid(), 'Villapinzón', 'DEPT-25'),
(gen_random_uuid(), 'Villeta', 'DEPT-25'), (gen_random_uuid(), 'Viotá', 'DEPT-25'), (gen_random_uuid(), 'Yacopí', 'DEPT-25'), (gen_random_uuid(), 'Zipacón', 'DEPT-25'),
(gen_random_uuid(), 'Zipaquirá', 'DEPT-25'),

-- VALLE DEL CAUCA (76)
(gen_random_uuid(), 'Cali', 'DEPT-76'), (gen_random_uuid(), 'Alcalá', 'DEPT-76'), (gen_random_uuid(), 'Andalucía', 'DEPT-76'), (gen_random_uuid(), 'Ansermanuevo', 'DEPT-76'),
(gen_random_uuid(), 'Argelia', 'DEPT-76'), (gen_random_uuid(), 'Bolívar', 'DEPT-76'), (gen_random_uuid(), 'Buenaventura', 'DEPT-76'), (gen_random_uuid(), 'Guadalajara de Buga', 'DEPT-76'),
(gen_random_uuid(), 'Bugalagrande', 'DEPT-76'), (gen_random_uuid(), 'Caicedonia', 'DEPT-76'), (gen_random_uuid(), 'Calima', 'DEPT-76'), (gen_random_uuid(), 'Candelaria', 'DEPT-76'),
(gen_random_uuid(), 'Cartago', 'DEPT-76'), (gen_random_uuid(), 'Dagua', 'DEPT-76'), (gen_random_uuid(), 'El Águila', 'DEPT-76'), (gen_random_uuid(), 'El Cairo', 'DEPT-76'),
(gen_random_uuid(), 'El Cerrito', 'DEPT-76'), (gen_random_uuid(), 'El Dovio', 'DEPT-76'), (gen_random_uuid(), 'Florida', 'DEPT-76'), (gen_random_uuid(), 'Ginebra', 'DEPT-76'),
(gen_random_uuid(), 'Guacarí', 'DEPT-76'), (gen_random_uuid(), 'Jamundí', 'DEPT-76'), (gen_random_uuid(), 'La Cumbre', 'DEPT-76'), (gen_random_uuid(), 'La Unión', 'DEPT-76'),
(gen_random_uuid(), 'La Victoria', 'DEPT-76'), (gen_random_uuid(), 'Obando', 'DEPT-76'), (gen_random_uuid(), 'Palmira', 'DEPT-76'), (gen_random_uuid(), 'Pradera', 'DEPT-76'),
(gen_random_uuid(), 'Restrepo', 'DEPT-76'), (gen_random_uuid(), 'Riofrío', 'DEPT-76'), (gen_random_uuid(), 'Roldanillo', 'DEPT-76'), (gen_random_uuid(), 'San Pedro', 'DEPT-76'),
(gen_random_uuid(), 'Sevilla', 'DEPT-76'), (gen_random_uuid(), 'Toro', 'DEPT-76'), (gen_random_uuid(), 'Trujillo', 'DEPT-76'), (gen_random_uuid(), 'Tuluá', 'DEPT-76'),
(gen_random_uuid(), 'Ulloa', 'DEPT-76'), (gen_random_uuid(), 'Versalles', 'DEPT-76'), (gen_random_uuid(), 'Vijes', 'DEPT-76'), (gen_random_uuid(), 'Yotoco', 'DEPT-76'),
(gen_random_uuid(), 'Yumbo', 'DEPT-76'), (gen_random_uuid(), 'Zarzal', 'DEPT-76'),

-- (Se podrían añadir más bloques aquí para los ~1100 municipios)
-- NOTA: Con estos bloques cubrimos los departamentos más masivos operativamente.
(gen_random_uuid(), 'Leticia', 'DEPT-91'), (gen_random_uuid(), 'Arauca', 'DEPT-81'), (gen_random_uuid(), 'Sincelejo', 'DEPT-70'), (gen_random_uuid(), 'Corozal', 'DEPT-70'),
(gen_random_uuid(), 'Neiva', 'DEPT-41'), (gen_random_uuid(), 'Pitalito', 'DEPT-41'), (gen_random_uuid(), 'Ibagué', 'DEPT-73'), (gen_random_uuid(), 'Espinal', 'DEPT-73'),
(gen_random_uuid(), 'Barrancabermeja', 'DEPT-68'), (gen_random_uuid(), 'Bucaramanga', 'DEPT-68'), (gen_random_uuid(), 'Cúcuta', 'DEPT-54'), (gen_random_uuid(), 'Pasto', 'DEPT-52'),
(gen_random_uuid(), 'Popayán', 'DEPT-19'), (gen_random_uuid(), 'Valledupar', 'DEPT-20'), (gen_random_uuid(), 'Villavicencio', 'DEPT-50'), (gen_random_uuid(), 'Pereira', 'DEPT-66'),
(gen_random_uuid(), 'Armenia', 'DEPT-63'), (gen_random_uuid(), 'Manizales', 'DEPT-17'), (gen_random_uuid(), 'Quibdó', 'DEPT-27'), (gen_random_uuid(), 'Riohacha', 'DEPT-44'),
(gen_random_uuid(), 'Santa Marta', 'DEPT-47'), (gen_random_uuid(), 'Montería', 'DEPT-23'), (gen_random_uuid(), 'San Andrés', 'DEPT-88'), (gen_random_uuid(), 'Yopal', 'DEPT-85'),
(gen_random_uuid(), 'Florencia', 'DEPT-18'), (gen_random_uuid(), 'Mocoa', 'DEPT-86'), (gen_random_uuid(), 'San José del Guaviare', 'DEPT-95'), (gen_random_uuid(), 'Puerto Inírida', 'DEPT-94'),
(gen_random_uuid(), 'Mitú', 'DEPT-97'), (gen_random_uuid(), 'Puerto Carreño', 'DEPT-99')

ON CONFLICT (region_id, name) DO NOTHING;
